# Generated by Django 4.0.5 on 2023-04-06 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pofileimg',
            new_name='profileimg',
        ),
    ]
