# Generated by Django 4.0.5 on 2023-04-10 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_followerscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followerscount',
            old_name='followers',
            new_name='follower',
        ),
    ]
